<?php

return [
    // PUBLIC
    "HOMEPAGE",

    // User-related items
    "USER_DASHBOARD",
    "USER_DOCUMENTS",
    "USER_SKILL_CHECKLIST",

    // Agency-related items
    "AGENCY_DASHBOARD",
    "AGENCY_APPLICANTS",
    "AGENCY_CANDIDATES",
    "AGENCY_EMPLOYEES",
    "AGENCY_FOLLOW_UP",
    "AGENCY_OFFICE_ADMINS",
    "AGENCY_SKILL_CHECKLIST",
    "AGENCY_TASKS",

    // Facility-related items
    "FACILITY_DASHBOARD",
    "FACILITY_APPLICANTS",
    "FACILITY_CANDIDATES",
    "FACILITY_EMPLOYEES",
    "FACILITY_FOLLOW_UP",
    "FACILITY_OFFICE_ADMINS",
    "FACILITY_SKILL_CHECKLIST",
    "FACILITY_TASKS",
    "FACILITY_COMPLIANCE",

    
    // Admin-related items
    "DASHBOARD"
];

?>
